
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int texto = 12;
  public static final int elementos_raiz = 3;
  public static final int agrupacion_contenido = 8;
  public static final int metadatos_titulo = 5;
  public static final int numero = 13;
  public static final int atributos_tabla = 10;
  public static final int ERROR = 23;
  public static final int informacion_tabulada = 9;
  public static final int direccion = 17;
  public static final int vinculo = 18;
  public static final int metadatos_cabecera = 4;
  public static final int secciones_encabezado = 7;
  public static final int tipo_documento = 2;
  public static final int imagen = 22;
  public static final int EOF = 0;
  public static final int correo = 14;
  public static final int secciones_cuerpo = 6;
  public static final int error = 1;
  public static final int listas_item = 20;
  public static final int negrita = 16;
  public static final int listas = 19;
  public static final int salto_linea = 15;
  public static final int operacion = 11;
  public static final int url_local = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tipo_documento",
  "elementos_raiz",
  "metadatos_cabecera",
  "metadatos_titulo",
  "secciones_cuerpo",
  "secciones_encabezado",
  "agrupacion_contenido",
  "informacion_tabulada",
  "atributos_tabla",
  "operacion",
  "texto",
  "numero",
  "correo",
  "salto_linea",
  "negrita",
  "direccion",
  "vinculo",
  "listas",
  "listas_item",
  "url_local",
  "imagen",
  "ERROR"
  };
}

